#!/usr/bin/env python3
"""
Assembles part1_llm.ipynb from the real source files and the real logged
outputs of your completed run. Run this FROM INSIDE:
    Data_266-Lab1/task1_llm/ritika_mukesh_neema/src/

    cd ~/Desktop/Data_266-Lab1/task1_llm/ritika_mukesh_neema/src
    python3 build_notebook.py

It reads your actual .py files and actual outputs/*.json|.md|.txt|.png (no
fabricated numbers), and writes part1_llm.ipynb next to this script.
"""
import base64
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MEMBER = os.path.dirname(HERE)          # .../ritika_mukesh_neema
OUT = os.path.join(MEMBER, "outputs")


def read(path, default=""):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print(f"  [warn] missing: {path}")
        return default


def code_cell(source, outputs=None):
    return {
        "cell_type": "code",
        "execution_count": 1,
        "metadata": {},
        "outputs": outputs or [],
        "source": source.splitlines(keepends=True),
    }


def md_cell(source):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def stream_output(text):
    return [{"output_type": "stream", "name": "stdout", "text": text.splitlines(keepends=True)}]


def image_output(png_path):
    try:
        with open(png_path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        return [{
            "output_type": "display_data",
            "data": {"image/png": b64, "text/plain": ["<Figure: loss curve>"]},
            "metadata": {},
        }]
    except FileNotFoundError:
        print(f"  [warn] missing image: {png_path}")
        return []


def tail_lines(text, n=40):
    lines = text.strip().splitlines()
    return "\n".join(lines[-n:])


def main():
    cells = []

    cells.append(md_cell(
        "# Task 1 — GPT-Style LLM From Scratch on TinyStories\n"
        "**Author:** Ritika Mukesh Neema\n\n"
        "This notebook contains the full pipeline (data prep -> model -> training -> "
        "metrics -> generation) used to produce the results in `results.md` and "
        "`failure_analysis.md`. Code cells are the real source from `src/*.py`; "
        "output cells below the training/generation cells are the real captured "
        "output from the completed run (see `outputs/train_log.jsonl` and "
        "`outputs/generation_metrics.json`)."
    ))

    # --- source code cells ---
    for fname, title in [
        ("data.py", "## Data loading & encoding"),
        ("model.py", "## Model — hand-rolled GPT (causal self-attention, LayerNorm, GELU FFN)"),
        ("metrics.py", "## Metrics utilities"),
        ("train.py", "## Training loop"),
        ("generate.py", "## Generation & failure-case sampling"),
    ]:
        path = os.path.join(HERE, fname)
        src = read(path)
        if not src:
            continue
        cells.append(md_cell(title))
        cells.append(code_cell(src))

    # --- real training output ---
    train_log = read(os.path.join(OUT, "train_log.jsonl"))
    train_metrics = read(os.path.join(OUT, "train_metrics.json"))
    metrics_report = read(os.path.join(OUT, "metrics_report.md"))

    cells.append(md_cell("## Run: `python run_all.py` (full run, seed=6638, 12 epochs)\n"
                          "Real console/log output from the completed training run:"))
    log_tail = tail_lines(train_log, 30) if train_log else "(train_log.jsonl not found)"
    cells.append(code_cell(
        "# Captured from outputs/train_log.jsonl (last 30 lines) — not re-executed here\n"
        "print(open('../outputs/train_log.jsonl').read())",
        outputs=stream_output(log_tail),
    ))

    if train_metrics:
        cells.append(md_cell("### Final train_metrics.json"))
        cells.append(code_cell(
            "import json\nprint(json.dumps(json.load(open('../outputs/train_metrics.json')), indent=2))",
            outputs=stream_output(json.dumps(json.loads(train_metrics), indent=2)),
        ))

    # loss curve image
    cells.append(md_cell("### Loss curve"))
    cells.append(code_cell(
        "from IPython.display import Image\nImage('../outputs/loss_curve.png')",
        outputs=image_output(os.path.join(OUT, "loss_curve.png")),
    ))

    if metrics_report:
        cells.append(md_cell("### metrics_report.md (auto-generated by train.py)"))
        cells.append(md_cell(metrics_report))

    # --- generation output ---
    gen_metrics = read(os.path.join(OUT, "generation_metrics.json"))
    gen_samples = read(os.path.join(OUT, "generated_samples.txt"))

    cells.append(md_cell("## Run: `python generate.py`\nReal captured output:"))
    if gen_metrics:
        cells.append(code_cell(
            "import json\nprint(json.dumps(json.load(open('../outputs/generation_metrics.json')), indent=2))",
            outputs=stream_output(json.dumps(json.loads(gen_metrics), indent=2)),
        ))
    if gen_samples:
        cells.append(md_cell("### Sample generations (`outputs/generated_samples.txt`, truncated)"))
        cells.append(code_cell(
            "print(open('../outputs/generated_samples.txt').read())",
            outputs=stream_output(tail_lines(gen_samples, 60)),
        ))

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    out_path = os.path.join(HERE, "part1_llm.ipynb")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1)
    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
